name: "Repository settings automation"
description: "Automate github repo settings"
inputs:
  diff:
    description: "Display a diff"
    required: true
    default: "true"
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}
